/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as test from "./test";
export type { test };
export type { BasicNFT } from "./BasicNFT";
export type { RandomIpfsNFT } from "./RandomIpfsNFT";
